### ISSUE TITLE
Delete Table Shortcut not working

### ISSUE THREAD

**Issue by shashwatdixit124** [shashwatdixit124/Jasper#2]
Delete Table functionality has been done ( accessible through tablecontent.jsp ) but shortcut has not been implemented yet ( in table.jsp ).
![github_issue](https://cloud.githubusercontent.com/assets/16637488/25070437/badcfda8-22bb-11e7-95ad-d01540b7b8a0.jpg)

deleteTable Servlet takes two post variable db and table , we have the value of db as dbname. 
TODO find a way to provide table name in modal form ( deleteTable ) given in table.jsp ( bottom ), can be done by javascript.

**Comment by vinay0410** [comment]
Did it using javascript as suggested by calling an onclick function which alters the value of the input tag used to send table name in the form tag.
